---
title: "Plots for Ibsen thesis"
author: "Sarah Hvid Andersen"
date: "4/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse)

```

```{r}
df <- read_csv('Results.csv')


df$model_data = paste0(df$model, df$data)
  
df <- df %>% mutate(model = as.factor(model),
                    data = as.factor(data),
                    mode = as.factor(mode),
                    model_data = as.factor(model_data),
                    F1_from = as.factor(F1_from))


df$model <- relevel(df$model, 'spacy_small')
df$model <- relevel(df$model, 'spacy_medium')
df$model <- relevel(df$model, 'spacy_large')
df$model <- relevel(df$model, 'spacy_trf')
df$model <- relevel(df$model, 'dacy_small')
df$model <- relevel(df$model, 'dacy_medium')
df$model <- relevel(df$model, 'dacy_large')


df$F1_from <- relevel(df$F1_from, 'Ibsen')


levels(df$model) 

```

```{r}

# comparing my results with the results on contemporary danish
df %>% filter(misc_or_type == 'false', mode == 'strict', data == 'x' | data == 'all') %>%  
  ggplot(aes(x=model, y=f1, fill=F1_from)) + 
  geom_bar(stat = 'identity', position='dodge') +
  geom_text(aes(label= round(f1, digits = 2)), position=position_dodge(width=0.9), vjust=-0.25) +
  coord_cartesian(ylim=c(0, 1)) + 
  scale_y_continuous(breaks=seq(0, 1, 0.05)) +
  ggtitle('F1-values by model', subtitle = "Results on Ibsen's letters vs. contemporary Danish")


df %>% filter(misc_or_type == 'true', mode == 'strict', data != 'all' & data != 'x') %>%
  group_by(model, data) %>% 
  ggplot(aes(x=model, y=f1, fill=mode)) + 
  geom_bar(stat = 'identity', position=position_dodge()) +
  coord_cartesian(ylim=c(0, 1)) + 
  scale_y_continuous(breaks=seq(0, 1, 0.1)) +
  facet_grid(.~data)+
  ggtitle('F1 scores by model', subtitle = 'By year, misc included') +
  coord_flip()


# number of predictions by model

df %>% filter(misc_or_type == 'false', data != 'all' & data != 'x') %>%
  group_by(model, data) %>% 
  ggplot(aes(x=model, y=no_of_predictions, fill = model)) + 
  geom_bar(stat = 'identity', position=position_dodge()) +
  coord_cartesian(ylim=c(0, 800)) + 
  facet_grid(.~data)+
  theme(axis.text.x=element_blank(), axis.title.x = element_blank()) +
  ggtitle('Number of predictions by model', subtitle = 'Divided by year, MISC excluded')

df %>% filter(misc_or_type == 'true', data != 'all' & data != 'x') %>%
  group_by(model, data) %>% 
  ggplot(aes(x=model, y=no_of_predictions, fill = model)) + 
  geom_bar(stat = 'identity', position=position_dodge()) +
  coord_cartesian(ylim=c(0, 800)) + 
  facet_grid(.~data)+
  theme(axis.text.x=element_blank(), axis.title.x = element_blank()) +
  ggtitle('Number of predictions by model', subtitle = 'Divided by year, MISC included')




```

